---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp:
  labels:
    app: hello
  name: hello
  namespace: prod
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        app: hello
    spec:
      containers:
      - image: 801f7402-kr1-registry.container.cloud.toast.com/gitops:v1.0.1
        name: nginx
        resources: {}
status: {}
